modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="chrono"
version="1.0.0"
displayName="Chrono Warden"
description='''
Chrono Warden from A Universal Time.
Time manipulation stand with Fast Forward, Halt, Tremor, Time Anchor and more.
'''

[[dependencies.chrono]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chrono]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
